[tool.poetry]
name = "mongosql"
version = "3.0.0"
description = "A JSON query engine with SqlAlchemy as a back-end"
authors = ["Dignio"]
repository = "https://github.com/dignio/kolypto-mongosql"


[tool.poetry.dependencies]
python = "^3.14"
sqlalchemy = '^1.4, < 2'
nplus1loader = { git = "https://github.com/dignio/kolypto-nplus1loader.git", branch = "master" } # TODO: Change to tag with sqlalchemy 1.4 support
looseversion = "^1.3.0"

[tool.poetry.group.dev.dependencies]
nox = "^2025.0"
pytest = "^9.0"
pytest-cov = "^7.0"
psycopg2-binary = '^2.8'
exdoc = '0.1.3' # TODO Kolypto private library (replace to something else)
flask_jsontools = {git = "https://github.com/dignio/kolypto-flask-jsontools.git", branch = "master"}  # TODO: Change to tag with sqlalchemy 1.4 support

[tool.pytest.ini_options]
testpaths = [
    "tests/",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
